package com.company;

public enum Names {
    BARN, BED, CAFE, ALFALFA, BREAD, CLINIC, WATERING_CAN, WOOL, WALL, POND,
    DINING_TABLE, FARM, FIELD, BRANCH, CHICKEN_MEAT, TOMATO_PASTE_MACHINE,
    OLD_LUMBER, PINE_LUMBER, OAK_LUMBER, FRUIT_GARDEN,TOMATO_PASTE,
    FRYING_PAN, KNIFE, MIXER, POT, OVEN, JUICE, JUICER, THREAD,
    GREENHOUSE, GYM, HOME, LABORATORY, MARKET, GROCERIES_STORE,
    ORANGE, POTATO, CARROT, GREENGAGE, MELON, FLOUR, SHEEP_MEAT,
    PINEAPPLE, STRAWBERRY, PEPPER, PEACH, PEAR, FISH_MEAT, STONE,
    GARLIC, PEAS, LETTUCE, EGGPLANT, LEMON, SPICE, COW_MEAT,
    POMEGRANATE, CUCUMBER, WATERMELON, ONION, TURNIP, APPLE,
    OIL, SALT, LEMON_JUICE, CHEESECAKE, SHIRAZI_SALAD, AGITATOR,
    MILK, CHEESE, EDG, SUGAR, MIRZAGHASEMI, FRENCH_FRIES, IRON_ORE,
    STORAGE_BOX, KITCHEN, CAVE, FOREST, CONVENTIONAL_DRUG, SILVER_ORE,
    POWERFUL_DRUG, BEST_DRUG, SPINNING_WHEEL, ULTIMATE_CHEESE_MAKER,
    STONE_SHOVEL, FERROUS_SHOVEL, SILVER_SHOVEL, ADAMANTIUM_SHOVEL,
    STONE_PICK, FERROUS_PICK, SILVER_PICK, ADAMANTIUM_PICK, ADAMANTIUM_ORE,
    STONE_AX, FERROUS_AX, SILVER_AX, ADAMANTIUM_AX, BUTCHERY,
    GENERAL_STORE, RANCH, RIVER, VIllage, WORKSHOP, TOMATO, PLANT,
    TREE, SEED, MILKER, ANIMAL_MEDICINE, FISHING_ROD_0, FISHING_ROD_1, FISHING_ROD_2, FISHING_ROD_3, SCCISSORS,
    PEACH_TREE, PEAR_TREE, LEMON_TREE, POMEGRANATE_TREE, APPLE_TREE, ORANGE_TREE, WEATHERMACHINE
}
